version: '3.4'

services:
  minio:
    image: minio/minio
    ports:
      - "9008:9000"
    command: "server /data"
    environment:
        - MINIO_ROOT_USER=gleam123
        - MINIO_ROOT_PASSWORD=gleam456
