name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: mosuka/minio:latest
        env:
          MINIO_ROOT_USER: gleam123
          MINIO_ROOT_PASSWORD: gleam456
        ports:
          - 9008:9000
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: erlef/setup-beam@v1.15.3
        with:
          otp-version: "25.3"
          gleam-version: "0.28.1"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
